import React, { useState } from "react";
import { Award, ArrowRight, ArrowLeft, CheckCircle2, Play, Sparkles } from "lucide-react";

interface JudgeDemoModeProps {
  onStepSelect: (tabId: string, sol?: number) => void;
  onExit: () => void;
}

interface DemoStep {
  step: number;
  tabId: string;
  title: string;
  narrative: string;
  actionLabel: string;
  targetSol?: number;
}

const DEMO_STEPS: DemoStep[] = [
  {
    step: 1,
    tabId: "overview",
    title: "1. Mission Overview & Environmental State",
    narrative: "Begin by inspecting the live telemetry gauges and 4,700+ Sols of continuous data coverage across Gale Crater and Elysium Planitia.",
    actionLabel: "View Mission Overview"
  },
  {
    step: 2,
    tabId: "explorer",
    title: "2. Multi-Mission Data Explorer",
    narrative: "Demonstrate authentic multi-dataset integration: switch between Curiosity (MSL) REMS and InSight (TWINS) meteorological series.",
    actionLabel: "Open Data Explorer"
  },
  {
    step: 3,
    tabId: "explorer",
    title: "3. Time-Series & Sensor Gap Analysis",
    narrative: "Inspect zoomable pressure and temperature time-series with normalized comparison mode and transparent sensor gap highlights.",
    actionLabel: "Examine Time Series"
  },
  {
    step: 4,
    tabId: "atmospheric",
    title: "4. Vertical Sounding Profiles (MRO MCS)",
    narrative: "Explore altitude vs. atmospheric variables (0 to 80 km) retrieved by the Mars Climate Sounder with 1-sigma uncertainty envelopes.",
    actionLabel: "Inspect Vertical Profiles"
  },
  {
    step: 5,
    tabId: "anomaly",
    title: "5. Dual-Mode Anomaly Intelligence",
    narrative: "Inspect the Anomaly Timeline generated by Multivariate Isolation Forest, flagging extreme dust lifting and diurnal thermal collapses.",
    actionLabel: "Open Anomaly Timeline"
  },
  {
    step: 6,
    tabId: "anomaly",
    title: "6. Signature WOW #1: Event Replay Reconstruct",
    narrative: "Reconstruct environmental state around Sol 2082: scrub through T - 12 Sols to T + 12 Sols to watch diurnal amplitude collapse.",
    actionLabel: "Launch Sol 2082 Replay",
    targetSol: 2082
  },
  {
    step: 7,
    tabId: "map",
    title: "7. Mars Topographic & Spatial Context",
    narrative: "Inspect landing site elevations relative to the MOLA Aeroid datum (-4.5 km in Gale Crater vs. -2.6 km in Elysium Planitia).",
    actionLabel: "Open Mars Spatial Map"
  },
  {
    step: 8,
    tabId: "meci",
    title: "8. Martian Environmental Challenge Index",
    narrative: "Inspect the transparent 0–100 MECI index score, component factor decomposition bars, and run a simulated What-If scenario.",
    actionLabel: "Inspect Challenge Index"
  },
  {
    step: 9,
    tabId: "model",
    title: "9. ML Model Lab & Failure Analysis",
    narrative: "Examine the baseline-first comparison table (Persistence vs. Random Forest) and honest slice-based seasonal error analysis.",
    actionLabel: "Open ML Model Lab"
  },
  {
    step: 10,
    tabId: "ai",
    title: "10. Signature WOW #2: Grounded AI Scientist",
    narrative: "Ask a scientific question adhering to the AI Answer Contract, with interactive [VIEW DATA] trace links back to the charts.",
    actionLabel: "Ask Mars AI Scientist"
  },
  {
    step: 11,
    tabId: "catalog",
    title: "11. NASA Data Catalog & Lineage",
    narrative: "Verify PDS collection identifiers, DOIs, calibration levels, and physical measurement bounds for all datasets.",
    actionLabel: "Inspect Data Catalog"
  },
  {
    step: 12,
    tabId: "notebook",
    title: "12. Science Methodology & Reproducibility",
    narrative: "Review the full mathematical derivations, Solar Longitude calculations, and scientific integrity disclaimers.",
    actionLabel: "Open Science Notebook"
  }
];

export const JudgeDemoMode: React.FC<JudgeDemoModeProps> = ({ onStepSelect, onExit }) => {
  const [currentStep, setCurrentStep] = useState<number>(0);

  const stepInfo = DEMO_STEPS[currentStep];

  const handleStepJump = (idx: number) => {
    setCurrentStep(idx);
    const target = DEMO_STEPS[idx];
    onStepSelect(target.tabId, target.targetSol);
  };

  const handleNext = () => {
    if (currentStep < DEMO_STEPS.length - 1) {
      handleStepJump(currentStep + 1);
    }
  };

  const handlePrev = () => {
    if (currentStep > 0) {
      handleStepJump(currentStep - 1);
    }
  };

  return (
    <div className="bg-mars-darkest border-2 border-mars-amber rounded-xl p-5 shadow-glow-amber space-y-4 font-mono text-xs">
      {/* Top Banner */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-mars-border pb-3">
        <div className="flex items-center gap-2">
          <Award className="w-5 h-5 text-mars-amber animate-bounce" />
          <div>
            <h2 className="text-sm font-bold text-white tracking-wide">
              NASA SPACE APPS CHALLENGE — JUDGE DEMONSTRATION MODE
            </h2>
            <p className="text-[11px] text-slate-400 font-sans">
              Guided 12-Step Evaluation Tour (Optimized for 2–4 minute competition judging).
            </p>
          </div>
        </div>

        <button
          onClick={onExit}
          className="px-3 py-1 rounded bg-mars-surface hover:bg-mars-panel border border-mars-border text-slate-300 hover:text-white self-start sm:self-center"
        >
          Exit Demo Mode
        </button>
      </div>

      {/* Current Step Progress Bar */}
      <div className="flex items-center gap-1 overflow-x-auto pb-1 scrollbar-none">
        {DEMO_STEPS.map((s, idx) => (
          <button
            key={s.step}
            onClick={() => handleStepJump(idx)}
            className={`flex-1 min-w-[28px] h-2 rounded-full transition-all ${
              idx === currentStep
                ? "bg-mars-amber ring-2 ring-mars-amber/50"
                : idx < currentStep
                ? "bg-emerald-500"
                : "bg-mars-surface"
            }`}
            title={s.title}
          />
        ))}
      </div>

      {/* Step Details & Action */}
      <div className="p-4 bg-mars-panel border border-mars-border rounded-lg space-y-3">
        <div className="flex justify-between items-center text-slate-400">
          <span className="text-mars-cyan font-bold">STEP {stepInfo.step} OF 12</span>
          <span>Target View: <strong className="text-white uppercase">{stepInfo.tabId}</strong></span>
        </div>

        <div>
          <h3 className="text-base font-bold text-white font-sans">{stepInfo.title}</h3>
          <p className="text-xs text-slate-300 font-sans mt-1 leading-relaxed">
            {stepInfo.narrative}
          </p>
        </div>

        <div className="flex flex-wrap items-center justify-between gap-3 pt-2">
          <div className="flex items-center gap-2">
            <button
              disabled={currentStep === 0}
              onClick={handlePrev}
              className="px-3 py-1.5 rounded bg-mars-surface border border-mars-border text-slate-300 disabled:opacity-30 hover:text-white flex items-center gap-1"
            >
              <ArrowLeft className="w-3.5 h-3.5" />
              <span>Previous</span>
            </button>
            <button
              disabled={currentStep >= DEMO_STEPS.length - 1}
              onClick={handleNext}
              className="px-3 py-1.5 rounded bg-mars-surface border border-mars-border text-slate-300 disabled:opacity-30 hover:text-white flex items-center gap-1"
            >
              <span>Next</span>
              <ArrowRight className="w-3.5 h-3.5" />
            </button>
          </div>

          <button
            onClick={() => onStepSelect(stepInfo.tabId, stepInfo.targetSol)}
            className="px-4 py-2 rounded bg-mars-amber hover:bg-mars-rust text-white font-bold transition-all shadow-glow-amber flex items-center gap-1.5"
          >
            <span>{stepInfo.actionLabel}</span>
            <Play className="w-3.5 h-3.5 fill-current" />
          </button>
        </div>
      </div>
    </div>
  );
};
